import type { Metadata } from "next";
import Navbar from "@/components/shared/navbar";
import "@/styles/globals.css";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Code Quest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-foreground text-text font-instrument-sans">
        <header>
          <Suspense fallback={<div className="p-4 text-center">Loading...</div>}>
            <Navbar />

          </Suspense>
        </header>

        <main className="max-w-7xl mx-auto bg-background min-h-screen rounded-border border border-border">
          <Suspense fallback={<div className="p-4 text-center">Loading...</div>}>
            {children}

          </Suspense>
        </main>
      </body>
    </html>
  );
}
